apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: kumari-46anjali-xms6-cc
  namespace: default
spec:
  encryptedData:
    TF_VAR_secret.: AQCgvSKIAN8SVc4TYvqBjwwn8AqonOpqokf9ctEEBpJ/R+HH1Z3AsCDyBQ2dt5uflO1ki2kfdlxcnwmzIwawkuqQJP1J2Rxw0UYgKETJAIk6D0vTAaL2/WyBt8xjRWQbB6HHtGDPxKR9PmL9tiYyv87/AFiCvAP6XoIT66zvLr6NxrljAHh4SIXUZWgCot3XEyA4XfX0AmYJIl9cJ6jDa3ceP1oTrHUKQftAGoC0zUeAm8Mx5qW/1PSogT29v0Iz6p+9cFiJHW9dqN3Z/AtLKzJinlr8KgXGFpmCvnzXiKRDvTwdwl9YLlYTCxMtacBcM5+CoDYfs1aGhosGkFMe2Bp/URgmEep+fkXIurDJUayHrho+yp1HOT0JHESB
  template:
    metadata:
      creationTimestamp: null
      name: kumari-46anjali-xms6-cc
      namespace: default

