apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: kumari-46anjali-xms6-cc
  namespace: default
spec:
  encryptedData:
    TF_VAR_secret.: AQBKgSt001GutW5qSnxDhkEu1TBUDJazLeaMuDVYx3Et+ii181uKs6Lzc9Ca8pRpqXsYp3KTMyKVu44VQ4ukq6zu/h6ZquKhoZSCe8en273UptlNbyJEz+IFaO775SnGUBpuehLWnMuA6VBRTv8n7ao/D0qP2F+r29TPNQC/qTfwbhcyW+RhyF4CGeHlOTNNdEV6yUtAwSUAYKYiqDyBLOJYPbXlMa8IRUDygOZX8GrSN89QJaIbnPUl5xrgwg8NYegrnJGArtqVL+X0Ry3io1d3j7T8cHuq05l9Y+yhpXIge0aOs+JVmSfprcbCBmqIKgTwO6dnAtRuad15cBxEoovL/4Q62FBSVP2R1I/DUK+G02apCK5pMoGCD8QP
  template:
    metadata:
      creationTimestamp: null
      name: kumari-46anjali-xms6-cc
      namespace: default

