apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: kumari-46anjali-xms6-cc
  namespace: default
spec:
  encryptedData:
    TF_VAR_secret.: AQCcLH5rOAJw/F2R/XD9NMdhCya4xD2FzgfAfOF6qt5Ywan+Ho+b4Krba1Mo25eTdKEOoa0OaOQyfBFoz4dKGTAU5rYuLGAfpqduSzMn9HLxi9OOXzfrw6mZAvZr4LXgv9azBMPsVotwBIB4gYJu8CC581kcPCy8nYhVkwSnvV8TEwLAMWl2w1TEjrSJVuqnIknqlXlz0SvfWrC4iBmUX+fk7buKgfb5fHggF4RbEw8FCDIiIrixrQan8oSnrR4pxzNbmUx+WHdvk0WI6PTWIn7dDkDjllm2vo7DhSSrVjoroWiVoIUEx9KLCkrhirGXqeMOOs1AeQgHV41Y9/JgyPK17Xttd7E+vYF3TJFBMPZTr05VwhDi+TpKHPYW
  template:
    metadata:
      creationTimestamp: null
      name: kumari-46anjali-xms6-cc
      namespace: default

