apiVersion: eaas.envmgmt.io/v1
kind: Environment
metadata:
  name: kumari-46anjali-xms6-env3
  project: kumari-46anjali-xms6
spec:
  reconcile_resources:
  - name: kumari-46anjali-xms6-rt
  template:
    name: kumari-46anjali-xms6-et
    version: v1
    versionState: unspecified
