apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: kumari-46anjali-xms6-cc
  namespace: default
spec:
  encryptedData:
    TF_VAR_secret.: AQBKp3ZJW+GukKlLHQq9By+liM2keKF2nDKiOunUIsjGQbDWuw2A05+D8G3JNgXdmpq24MG81ekH0xPpiDlXap1fTHjfREaqepLqD/9cDqH8pZGdIyGAwJQv/S95jGuexOJBxOTItuNK7ymBhxREAljZWjDiOfxKiFVMgPzWU62N2PkOIlJzoJhX5tNqspzsiSarSK4lCPiWkQs2n8rfinsdvobvQomF4I2QojTU63ssLXqmjzv5y9kueTp2Y8M++ipLJYEBTFjQbMuOTzBTf0JSSBPnUt/xz+hTRess8o0uk2cPbog0b+370YafF5lPINYkLRBfsdzfY3Rn6b4zMLNG26nfSPp4dli315ViWt64EqNHh06yShzHDn75
  template:
    metadata:
      creationTimestamp: null
      name: kumari-46anjali-xms6-cc
      namespace: default

