apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: kumari-46anjali-xms6-rafay-cc
  namespace: default
spec:
  encryptedData:
    RCTL_API_KEY.: AQAfLZRIXtvnBLXtX37SR1WXaXKhJEkwGgCQUpy5QG9PaqD/+zAsLG8nle5TMmeeCDRkMSQos5GDLzYX/qgXFzf7GgsbRS4vl6HfQ/WfgBOhQjGZML1+q2U9+jN5VoZbjQuoxecLL+bkeXBSH2d0b7bWqP92MjuswHcZ6OTEKpiVhF4rmWW6Lgjw0O7r6ct2dT0WdrhDQHY17C7EeSaZaM/fC33P3C6d5TmZXR5Tr9d1jYknOC1JlqJW8Ry8cFfO+v5xCVacg565H9gYMia84GZn7IqR9dDUnbA4UjBNEcJnvoBfplmROdzJgUxAEMhG092iSUoi2xxooCR6RpnNr4w8cKu8PMGiXblt2+fvdDfIfG10GUJLxdp4QxrUjNLA31wFj4+mFW7Ocvj9LgxHyDkZ3U6NR34Oy+RidLId76QX8wbYGm3DTX9TGy6cUPoGQs+4ek0kmU0sZytIG6TcRljk88J1ht9wRHpNShXwKVcTRQxEvcTCIHu3Jq5go2E=
    RCTL_API_SECRET.: AQCC9ZShxOGiFxw00VttKnNF8Aa5he7yl/r3GEHYoeb/Z6H5l4/n4jBAKtTobEu1+ucLIIrYMXMphmn94uuXfuHRvsjjUvGTdO7IvX08Ik5Bia8gi5MaAS57cX5Yp18pLxhfjgc2AFrE6ZNg9e9gI/ZDVNpvrIkT1s+doAopu8wO/bk1aqQ+KKLe49qIejfjxqflxcTupn2cYmHMmDpxOLmOfHw++kY1ROc0BS2JoF3mk4KsmdhITci5xUVvD0r2s5L2/n0BgTFXIbjLNMMU2+wMfUCvf3UVtU2Kc4TE//oE4X/pN2nc3IcRe8uaIIVmRs4Ro1OBl1Lp3c71cVuejC8c3ffLUYL6Xt6o4gpnNzq/NoJRG1Got5es5Nf232AJzVSjhkpN8eu3ShCaXbL9R1BVnnxTIMWtfBJelvJNIpqY1zQvDS6SqbQgKpLOlm03Et4=
  template:
    metadata:
      creationTimestamp: null
      name: kumari-46anjali-xms6-rafay-cc
      namespace: default

